/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.mainmethod0126.search.condition.metadata;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() throws ClassNotFoundException {
        App classUnderTest = new App();

        MetaDataContainer metaDataContainer = MetaDataContainer.getInstance();
        metaDataContainer.setBasePackage("io.github.mainmethod0126.springsearchconditionmetadatageneratorsample");
        metaDataContainer.scan();

        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
